// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujmopecebcracfoantqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqbW9wZWNlYmNyYWNmb2FudHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDg5NTIsImV4cCI6MjA1ODIyNDk1Mn0.L1fExAHMov-PUH38ybiPOnFtxLl-H0VpUZvpE2wlMbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);